// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: google/protobuf/c_sharp_features.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface CSharpFeatures {}

function createBaseCSharpFeatures(): CSharpFeatures {
	return {};
}

export const CSharpFeatures: MessageFns<CSharpFeatures> = {
	encode(
		_: CSharpFeatures,
		writer: BinaryWriter = new BinaryWriter(),
	): BinaryWriter {
		return writer;
	},

	decode(input: BinaryReader | Uint8Array, length?: number): CSharpFeatures {
		const reader =
			input instanceof BinaryReader ? input : new BinaryReader(input);
		const end = length === undefined ? reader.len : reader.pos + length;
		const message = createBaseCSharpFeatures();
		while (reader.pos < end) {
			const tag = reader.uint32();
			switch (tag >>> 3) {
			}
			if ((tag & 7) === 4 || tag === 0) {
				break;
			}
			reader.skip(tag & 7);
		}
		return message;
	},

	fromJSON(_: any): CSharpFeatures {
		return {};
	},

	toJSON(_: CSharpFeatures): unknown {
		const obj: any = {};
		return obj;
	},

	create<I extends Exact<DeepPartial<CSharpFeatures>, I>>(
		base?: I,
	): CSharpFeatures {
		return CSharpFeatures.fromPartial(base ?? ({} as any));
	},
	fromPartial<I extends Exact<DeepPartial<CSharpFeatures>, I>>(
		_: I,
	): CSharpFeatures {
		const message = createBaseCSharpFeatures();
		return message;
	},
};

type Builtin =
	| Date
	| Function
	| Uint8Array
	| string
	| number
	| boolean
	| undefined;

type DeepPartial<T> = T extends Builtin
	? T
	: T extends globalThis.Array<infer U>
		? globalThis.Array<DeepPartial<U>>
		: T extends ReadonlyArray<infer U>
			? ReadonlyArray<DeepPartial<U>>
			: T extends {}
				? { [K in keyof T]?: DeepPartial<T[K]> }
				: Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin
	? P
	: P & { [K in keyof P]: Exact<P[K], I[K]> } & {
			[K in Exclude<keyof I, KeysOfUnion<P>>]: never;
		};

interface MessageFns<T> {
	encode(message: T, writer?: BinaryWriter): BinaryWriter;
	decode(input: BinaryReader | Uint8Array, length?: number): T;
	fromJSON(object: any): T;
	toJSON(message: T): unknown;
	create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
	fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
